version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: trustflow-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  mongo:
    image: mongo:6
    container_name: trustflow_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: trustflow_rabbit
    ports:
    - "5672:5672"      # porta AMQP
    - "15672:15672"    # interfaccia web

volumes:
  pgdata:
  mongo_data:
