server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/documentdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000