server:
  port: 8083

spring:
  application:
    name: audit-service
    mongodb:
      uri: mongodb://localhost:27017/auditdb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest