server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/documentdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

integration:
  client-id: "demo-client"
  client-secret: "secret"
  oauth-token-url: "http://localhost:9000/oauth2/token"
  firma-digitale: "http://localhost:9000/api/external-services/firma-digitale"
  invio-documento: "http://localhost:9000/api/external-services/invio-documento"